### ISSUE TITLE
Config file with more than 34 accounts not writing to log

### ISSUE THREAD

**Issue by Serion717** [willguxy/AutoAmex#2]
I have more than 34 Amex accounts and for some reason the log doesn't show anything past the 34th account.  In fact, it seems to stop logging right after printing the name of the account.

**Comment by willguxy** [comment]
is this repeatable? I'd imagine the program got stuck in that case.

I have 48 accounts and it seems to work on my end.

**Comment by Serion717** [comment]
Yes, it happens everytime.  Usually it gets stuck on the first run on #38. Then it gets random

**Comment by doggpound007** [comment]
This also happens to me.  My work around is to run the script with my "full" config file a couple of times until the offers are completed on the first X number of cards.  Then I delete those cards from the config file, run the script again and it then adds all of the offers to the next X number of cards.  The script is awesome and I was hopeful there is just some little tweak that can be made to make it work on all of your cards.  Any help would be fantastic.  Thanks again !

**Comment by willguxy** [comment]
Is this still outstanding? I've made a few fixes. Now it works with the new AMEX Gui as well.

Appreciate it if anyone can try `python autoamex.py`. It will use the chrome driver. I've been using the same locally and no problem so far for me.

**Comment by doggpound007** [comment]
This appears to be functional !!
